services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data


volumes:
  local_pgdata:
  pgadmin-data:
  redis:
